// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ClearDriverLocationReducer from "../clear_driver_location_reducer";
import RecordDispatchEventReducer from "../record_dispatch_event_reducer";
import RecordDriverLocationReducer from "../record_driver_location_reducer";

export type ClearDriverLocationParams = __Infer<typeof ClearDriverLocationReducer>;
export type RecordDispatchEventParams = __Infer<typeof RecordDispatchEventReducer>;
export type RecordDriverLocationParams = __Infer<typeof RecordDriverLocationReducer>;

