// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  eventId: __t.string().primaryKey().name("event_id"),
  vendorId: __t.i32().name("vendor_id"),
  routeUuid: __t.string().name("route_uuid"),
  stopUuid: __t.string().name("stop_uuid"),
  driverUuid: __t.string().name("driver_uuid"),
  eventType: __t.string().name("event_type"),
  status: __t.string(),
  message: __t.string(),
  recordedAt: __t.string().name("recorded_at"),
});
