// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sampleId: __t.string().primaryKey().name("sample_id"),
  driverUuid: __t.string().name("driver_uuid"),
  userUuid: __t.string().name("user_uuid"),
  vendorId: __t.i32().name("vendor_id"),
  routeUuid: __t.string().name("route_uuid"),
  latitude: __t.f64(),
  longitude: __t.f64(),
  speedMps: __t.f64().name("speed_mps"),
  previousSpeedMps: __t.f64().name("previous_speed_mps"),
  hardBrake: __t.bool().name("hard_brake"),
  hardBrakeDeltaMps: __t.f64().name("hard_brake_delta_mps"),
  crashDetected: __t.bool().name("crash_detected"),
  fallDetected: __t.bool().name("fall_detected"),
  source: __t.string(),
  recordedAt: __t.string().name("recorded_at"),
});
