// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  eventId: __t.string(),
  vendorId: __t.i32(),
  routeUuid: __t.string(),
  stopUuid: __t.string(),
  driverUuid: __t.string(),
  eventType: __t.string(),
  status: __t.string(),
  message: __t.string(),
  recordedAt: __t.string(),
};
