// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  sampleId: __t.string(),
  driverUuid: __t.string(),
  userUuid: __t.string(),
  vendorId: __t.i32(),
  routeUuid: __t.string(),
  latitude: __t.f64(),
  longitude: __t.f64(),
  speedMps: __t.f64(),
  previousSpeedMps: __t.f64(),
  heading: __t.f64(),
  accuracyMeters: __t.f64(),
  hardBrake: __t.bool(),
  hardBrakeDeltaMps: __t.f64(),
  crashDetected: __t.bool(),
  fallDetected: __t.bool(),
  source: __t.string(),
  recordedAt: __t.string(),
};
