export type RootStackParamList = {
  Splash: undefined;
  WebView: undefined;
  LoginWebView: undefined;
  DashboardWebView: undefined;
  LoginHtmlView: undefined;
  DashboardHtmlView: undefined;
  NativeLogin: undefined;
  NativeRegister: undefined;
  NativeReset: undefined;
  Login: undefined;
  Register: undefined;
  Reset: undefined;
  Walkthrough: undefined;
  RoutesHome: undefined;
  RouteDetail: { route: import('./domain').RouteAssignment };
  OrderDetail: { stop: import('./domain').RouteStop; routeUuid: string };
  Home: { route?: import('./domain').RouteAssignment } | undefined;
  Profile: undefined;
};
